name: Check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Run Check Script
        run: deno run -A main.mjs
        env:
          INSTATUS_PAGE_ID: ${{ secrets.INSTATUS_PAGE_ID }}
          INSTATUS_API_KEY: ${{ secrets.INSTATUS_API_KEY }}
